ronin-app/config/routes.rb
Rails.application.routes.draw do
    root 'landing#index'
    get 'landing/info'
    get 'landing/exploit'
    get 'landing/ilh'
    get 'landing/portScan'

end

ronin-app/app/models/info_datum.rb
class InfoDatum < ActiveRecord::Base
end

ronin-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ronin-app/app/controllers/landing_controller.rb
require 'socket'
class LandingController < ApplicationController
    def index
    end
    
    def info
    end

    def exploit
    end

    def ilh
        #for when you want information regarding you local host
        @s = Socket.getaddrinfo("localhost",nil)
    end 
    def portScan
#        @socket = Socket.new(::INET, ::SOCK_STREAM)
         @pre = TellMeImPretty.new("Aastha")
        @t = @pre.pretty
    end   
end

ronin-app/app/helpers/application_helper.rb
module ApplicationHelper
end

ronin-app/app/helpers/landing_helper.rb
module LandingHelper
end

ronin-app/app/views/landing/ilh.html.erb
<h3><%= @s%></h3>

ronin-app/app/views/landing/index.html.erb
<h1>Welcome to Ronin:Attack and Penetration Testing Tool</h1>
    <ol><%= link_to 'Information Gathering', landing_info_path%></ol>
    <ol><%=link_to 'Exploitations', landing_exploit_path%></ol>
        

ronin-app/app/views/landing/info.html.erb
<%= form_for :landing do |f|%>
<h1>Information Gathering</h1>

<h3>Get Local host information:</h3>
    <%=link_to '<button>Data</button>'.html_safe, landing_ilh_path %>
<h3>Open Ports</h3>
   <p> <%= link_to 'port scan', landing_portScan_path%><p>    
<%end%>

ronin-app/app/views/landing/portScan.html.erb
<h1>Ports that are open</h1>
<p> <%= @t%></p>

ronin-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ronin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>